# Also see _includes/intro.html to customize the description which gets included in index.html.
includes_dir: ./template/_includes
layouts_dir: ./template/_layouts
data_dir: ./_docs
include: ["template/index.html"]

# Links
hostname: solace.com
docs-vmr-setup: //docs.solace.com/Solace-VMR-Set-Up/Setting-Up-VMRs.htm
solace-apis-cloud:
  - value: //solace.com/samples/solace-samples-c/
    name: C
  - value: //solace.com/samples/solace-samples-dotnet/
    name: C#/.NET
  - value: //solace.com/samples/solace-samples-java/
    name: Java
  - value: //solace.com/samples/solace-samples-javarto/
    name: Java RTO
  - value: //solace.com/samples/solace-samples-javascript/
    name: JavaScript
  - value: //solace.com/samples/solace-samples-nodejs/
    name: Node.js
open-apis-cloud:
  - value: //cloud.solace.com/samples/solace-samples-amqp-qpid-jms1/
    name: AMQP - JMS 1.1
  - value: //solace.com/samples/solace-samples-amqp-qpid-jms2/
    name: AMQP - JMS 2.0
  - value: //solace.com/samples/solace-samples-amqp-nodejs/
    name: AMQP - Node.js
  - value: //solace.com/samples/solace-samples-mqtt/
    name: MQTT - Eclipse Paho Java
  - value: //cloud.solace.com/samples/solace-samples-amqp-qpid-jms1/
    name: JMS 1.1 - Apache Qpid
  - value: //solace.com/samples/solace-samples-amqp-qpid-jms2/
    name: JMS 2.0 - Apache Qpid
  - value: //solace.com/samples/solace-samples-jms/
    name: JMS 1.1 - Solace
  - value: //solace.com/samples/solace-samples-openmama/
    name: OpenMAMA
  - value: //solace.com/samples/solace-samples-rest-messaging/
    name: REST Messaging
other-environments-dev:
  - value: //dev.solace.com/get-started/pcf-tutorials/
    name: Pivotal Cloud Foundry

#----------------------------------------------------
# Generally don't modify items below this point
url: "solacesamples.github.io" # the base hostname & protocol for your site

# Google services
google_analytics: UA-3921398-7

# Build settings
markdown: kramdown

collections:
  docs:
    output: true
    permalink: /:path/
